### PR TITLE
Improve step1

### PR DESCRIPTION
**Pull request by Avenred**
Instructing the user to download from the releases page is better then requesting them to clone the repo.
This prevents users from downloading potentially unstable development code and instead makes them stick to the releases.

### CODE REVIEW

**Comment by spencermacca** [comment]
Can you make the image linked a bit bigger before I merge?

**Comment by Avenred** [comment]
The image is 2560 x 1140, I'm sure that big enough?

**Comment by spencermacca** [comment]
For me it appears quite small

**Comment by spencermacca** [comment]
For me it appears quite small

**Comment by Avenred** [comment]
Hmm, I don't know why that's happening since the image is actually quite big.
Maybe there's an issue with the markdown itself?

**Comment by Avenred** [comment]
Okay I fixed it

**Comment by Avenred** [comment]
As it turns out, the width of step1.png was quite small and this caused the image to be (you guessed it,) quite small. Changed the width to 1000 to make everything more readable.
All good to merge? @SpencerComputers

**Comment by spencermacca** [comment]
Perfect, merging now 👍

**Pull request merged**
